/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using AWSECommerceService.Standard.Controllers;
using AWSECommerceService.Standard.Http.Client;
using AWSECommerceService.Standard.Utilities;

namespace AWSECommerceService.Standard
{
    public partial class AWSECommerceServiceClient
    {

        /// <summary>
        /// Singleton access to AWSECommerceServiceBinding controller
        /// </summary>
        public AWSECommerceServiceBindingController AWSECommerceServiceBinding
        {
            get
            {
                return AWSECommerceServiceBindingController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public AWSECommerceServiceClient() { }
        #endregion
    }
}