/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class CollectionSummary : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Price lowestListPrice;
        private Models.Price highestListPrice;
        private Models.Price lowestSalePrice;
        private Models.Price highestSalePrice;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestListPrice")]
        public Models.Price LowestListPrice 
        { 
            get 
            {
                return this.lowestListPrice; 
            } 
            set 
            {
                this.lowestListPrice = value;
                onPropertyChanged("LowestListPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestListPrice")]
        public Models.Price HighestListPrice 
        { 
            get 
            {
                return this.highestListPrice; 
            } 
            set 
            {
                this.highestListPrice = value;
                onPropertyChanged("HighestListPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestSalePrice")]
        public Models.Price LowestSalePrice 
        { 
            get 
            {
                return this.lowestSalePrice; 
            } 
            set 
            {
                this.lowestSalePrice = value;
                onPropertyChanged("LowestSalePrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestSalePrice")]
        public Models.Price HighestSalePrice 
        { 
            get 
            {
                return this.highestSalePrice; 
            } 
            set 
            {
                this.highestSalePrice = value;
                onPropertyChanged("HighestSalePrice");
            }
        }
    }
} 