/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class Collection : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.CollectionSummary collectionSummary;
        private Models.CollectionParent collectionParent;
        private List<Models.CollectionItem> collectionItem;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CollectionSummary")]
        public Models.CollectionSummary CollectionSummary 
        { 
            get 
            {
                return this.collectionSummary; 
            } 
            set 
            {
                this.collectionSummary = value;
                onPropertyChanged("CollectionSummary");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CollectionParent")]
        public Models.CollectionParent CollectionParent 
        { 
            get 
            {
                return this.collectionParent; 
            } 
            set 
            {
                this.collectionParent = value;
                onPropertyChanged("CollectionParent");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CollectionItem")]
        public List<Models.CollectionItem> CollectionItem 
        { 
            get 
            {
                return this.collectionItem; 
            } 
            set 
            {
                this.collectionItem = value;
                onPropertyChanged("CollectionItem");
            }
        }
    }
} 