/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class ImageSet : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string category;
        private Models.Image swatchImage;
        private Models.Image smallImage;
        private Models.Image thumbnailImage;
        private Models.Image tinyImage;
        private Models.Image mediumImage;
        private Models.Image largeImage;
        private Models.Image hiResImage;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Category")]
        public string Category 
        { 
            get 
            {
                return this.category; 
            } 
            set 
            {
                this.category = value;
                onPropertyChanged("Category");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SwatchImage")]
        public Models.Image SwatchImage 
        { 
            get 
            {
                return this.swatchImage; 
            } 
            set 
            {
                this.swatchImage = value;
                onPropertyChanged("SwatchImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SmallImage")]
        public Models.Image SmallImage 
        { 
            get 
            {
                return this.smallImage; 
            } 
            set 
            {
                this.smallImage = value;
                onPropertyChanged("SmallImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ThumbnailImage")]
        public Models.Image ThumbnailImage 
        { 
            get 
            {
                return this.thumbnailImage; 
            } 
            set 
            {
                this.thumbnailImage = value;
                onPropertyChanged("ThumbnailImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TinyImage")]
        public Models.Image TinyImage 
        { 
            get 
            {
                return this.tinyImage; 
            } 
            set 
            {
                this.tinyImage = value;
                onPropertyChanged("TinyImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MediumImage")]
        public Models.Image MediumImage 
        { 
            get 
            {
                return this.mediumImage; 
            } 
            set 
            {
                this.mediumImage = value;
                onPropertyChanged("MediumImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LargeImage")]
        public Models.Image LargeImage 
        { 
            get 
            {
                return this.largeImage; 
            } 
            set 
            {
                this.largeImage = value;
                onPropertyChanged("LargeImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HiResImage")]
        public Models.Image HiResImage 
        { 
            get 
            {
                return this.hiResImage; 
            } 
            set 
            {
                this.hiResImage = value;
                onPropertyChanged("HiResImage");
            }
        }
    }
} 