/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class Item28 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.ActionEnum? action;
        private string cartItemId;
        private int? quantity;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Action", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.ActionEnum? Action 
        { 
            get 
            {
                return this.action; 
            } 
            set 
            {
                this.action = value;
                onPropertyChanged("Action");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CartItemId")]
        public string CartItemId 
        { 
            get 
            {
                return this.cartItemId; 
            } 
            set 
            {
                this.cartItemId = value;
                onPropertyChanged("CartItemId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Quantity")]
        public int? Quantity 
        { 
            get 
            {
                return this.quantity; 
            } 
            set 
            {
                this.quantity = value;
                onPropertyChanged("Quantity");
            }
        }
    }
} 