/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class Item116 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string aSIN;
        private string parentASIN;
        private Models.Errors errors;
        private string detailPageURL;
        private Models.ItemLinks itemLinks;
        private string salesRank;
        private Models.Image smallImage;
        private Models.Image mediumImage;
        private Models.Image largeImage;
        private List<Models.ImageSets> imageSets;
        private Models.ItemAttributes itemAttributes;
        private Models.VariationAttributes variationAttributes;
        private List<Models.RelatedItems> relatedItems;
        private Models.Collections collections;
        private Models.Subjects subjects;
        private Models.OfferSummary offerSummary;
        private Models.Offers offers;
        private Models.RentalOffers rentalOffers;
        private Models.VariationSummary variationSummary;
        private Models.Variations variations;
        private Models.CustomerReviews customerReviews;
        private Models.EditorialReviews editorialReviews;
        private Models.SimilarProducts similarProducts;
        private Models.Accessories accessories;
        private Models.Tracks tracks;
        private Models.BrowseNodes browseNodes;
        private Models.AlternateVersions alternateVersions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ASIN")]
        public string ASIN 
        { 
            get 
            {
                return this.aSIN; 
            } 
            set 
            {
                this.aSIN = value;
                onPropertyChanged("ASIN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ParentASIN")]
        public string ParentASIN 
        { 
            get 
            {
                return this.parentASIN; 
            } 
            set 
            {
                this.parentASIN = value;
                onPropertyChanged("ParentASIN");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Errors")]
        public Models.Errors Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("DetailPageURL")]
        public string DetailPageURL 
        { 
            get 
            {
                return this.detailPageURL; 
            } 
            set 
            {
                this.detailPageURL = value;
                onPropertyChanged("DetailPageURL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemLinks")]
        public Models.ItemLinks ItemLinks 
        { 
            get 
            {
                return this.itemLinks; 
            } 
            set 
            {
                this.itemLinks = value;
                onPropertyChanged("ItemLinks");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SalesRank")]
        public string SalesRank 
        { 
            get 
            {
                return this.salesRank; 
            } 
            set 
            {
                this.salesRank = value;
                onPropertyChanged("SalesRank");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SmallImage")]
        public Models.Image SmallImage 
        { 
            get 
            {
                return this.smallImage; 
            } 
            set 
            {
                this.smallImage = value;
                onPropertyChanged("SmallImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MediumImage")]
        public Models.Image MediumImage 
        { 
            get 
            {
                return this.mediumImage; 
            } 
            set 
            {
                this.mediumImage = value;
                onPropertyChanged("MediumImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LargeImage")]
        public Models.Image LargeImage 
        { 
            get 
            {
                return this.largeImage; 
            } 
            set 
            {
                this.largeImage = value;
                onPropertyChanged("LargeImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ImageSets")]
        public List<Models.ImageSets> ImageSets 
        { 
            get 
            {
                return this.imageSets; 
            } 
            set 
            {
                this.imageSets = value;
                onPropertyChanged("ImageSets");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ItemAttributes")]
        public Models.ItemAttributes ItemAttributes 
        { 
            get 
            {
                return this.itemAttributes; 
            } 
            set 
            {
                this.itemAttributes = value;
                onPropertyChanged("ItemAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("VariationAttributes")]
        public Models.VariationAttributes VariationAttributes 
        { 
            get 
            {
                return this.variationAttributes; 
            } 
            set 
            {
                this.variationAttributes = value;
                onPropertyChanged("VariationAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RelatedItems")]
        public List<Models.RelatedItems> RelatedItems 
        { 
            get 
            {
                return this.relatedItems; 
            } 
            set 
            {
                this.relatedItems = value;
                onPropertyChanged("RelatedItems");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Collections")]
        public Models.Collections Collections 
        { 
            get 
            {
                return this.collections; 
            } 
            set 
            {
                this.collections = value;
                onPropertyChanged("Collections");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Subjects")]
        public Models.Subjects Subjects 
        { 
            get 
            {
                return this.subjects; 
            } 
            set 
            {
                this.subjects = value;
                onPropertyChanged("Subjects");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OfferSummary")]
        public Models.OfferSummary OfferSummary 
        { 
            get 
            {
                return this.offerSummary; 
            } 
            set 
            {
                this.offerSummary = value;
                onPropertyChanged("OfferSummary");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Offers")]
        public Models.Offers Offers 
        { 
            get 
            {
                return this.offers; 
            } 
            set 
            {
                this.offers = value;
                onPropertyChanged("Offers");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RentalOffers")]
        public Models.RentalOffers RentalOffers 
        { 
            get 
            {
                return this.rentalOffers; 
            } 
            set 
            {
                this.rentalOffers = value;
                onPropertyChanged("RentalOffers");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("VariationSummary")]
        public Models.VariationSummary VariationSummary 
        { 
            get 
            {
                return this.variationSummary; 
            } 
            set 
            {
                this.variationSummary = value;
                onPropertyChanged("VariationSummary");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Variations")]
        public Models.Variations Variations 
        { 
            get 
            {
                return this.variations; 
            } 
            set 
            {
                this.variations = value;
                onPropertyChanged("Variations");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CustomerReviews")]
        public Models.CustomerReviews CustomerReviews 
        { 
            get 
            {
                return this.customerReviews; 
            } 
            set 
            {
                this.customerReviews = value;
                onPropertyChanged("CustomerReviews");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("EditorialReviews")]
        public Models.EditorialReviews EditorialReviews 
        { 
            get 
            {
                return this.editorialReviews; 
            } 
            set 
            {
                this.editorialReviews = value;
                onPropertyChanged("EditorialReviews");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SimilarProducts")]
        public Models.SimilarProducts SimilarProducts 
        { 
            get 
            {
                return this.similarProducts; 
            } 
            set 
            {
                this.similarProducts = value;
                onPropertyChanged("SimilarProducts");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Accessories")]
        public Models.Accessories Accessories 
        { 
            get 
            {
                return this.accessories; 
            } 
            set 
            {
                this.accessories = value;
                onPropertyChanged("Accessories");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Tracks")]
        public Models.Tracks Tracks 
        { 
            get 
            {
                return this.tracks; 
            } 
            set 
            {
                this.tracks = value;
                onPropertyChanged("Tracks");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BrowseNodes")]
        public Models.BrowseNodes BrowseNodes 
        { 
            get 
            {
                return this.browseNodes; 
            } 
            set 
            {
                this.browseNodes = value;
                onPropertyChanged("BrowseNodes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AlternateVersions")]
        public Models.AlternateVersions AlternateVersions 
        { 
            get 
            {
                return this.alternateVersions; 
            } 
            set 
            {
                this.alternateVersions = value;
                onPropertyChanged("AlternateVersions");
            }
        }
    }
} 