/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class ItemLookupResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.OperationRequest operationRequest;
        private List<Models.Items117> items;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OperationRequest")]
        public Models.OperationRequest OperationRequest 
        { 
            get 
            {
                return this.operationRequest; 
            } 
            set 
            {
                this.operationRequest = value;
                onPropertyChanged("OperationRequest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Items")]
        public List<Models.Items117> Items 
        { 
            get 
            {
                return this.items; 
            } 
            set 
            {
                this.items = value;
                onPropertyChanged("Items");
            }
        }
    }
} 