/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class Offer : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Merchant merchant;
        private Models.OfferAttributes offerAttributes;
        private List<Models.OfferListing> offerListing;
        private Models.LoyaltyPoints loyaltyPoints;
        private Models.Promotions promotions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Merchant")]
        public Models.Merchant Merchant 
        { 
            get 
            {
                return this.merchant; 
            } 
            set 
            {
                this.merchant = value;
                onPropertyChanged("Merchant");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OfferAttributes")]
        public Models.OfferAttributes OfferAttributes 
        { 
            get 
            {
                return this.offerAttributes; 
            } 
            set 
            {
                this.offerAttributes = value;
                onPropertyChanged("OfferAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OfferListing")]
        public List<Models.OfferListing> OfferListing 
        { 
            get 
            {
                return this.offerListing; 
            } 
            set 
            {
                this.offerListing = value;
                onPropertyChanged("OfferListing");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LoyaltyPoints")]
        public Models.LoyaltyPoints LoyaltyPoints 
        { 
            get 
            {
                return this.loyaltyPoints; 
            } 
            set 
            {
                this.loyaltyPoints = value;
                onPropertyChanged("LoyaltyPoints");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Promotions")]
        public Models.Promotions Promotions 
        { 
            get 
            {
                return this.promotions; 
            } 
            set 
            {
                this.promotions = value;
                onPropertyChanged("Promotions");
            }
        }
    }
} 