/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class OfferListing : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string offerListingId;
        private string pricePerUnit;
        private Models.Price price;
        private Models.Price salePrice;
        private Models.Price amountSaved;
        private int? percentageSaved;
        private string availability;
        private Models.AvailabilityAttributes availabilityAttributes;
        private bool? isEligibleForSuperSaverShipping;
        private bool? isEligibleForPrimeFreeDigitalVideo;
        private bool? isEligibleForPrime;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OfferListingId")]
        public string OfferListingId 
        { 
            get 
            {
                return this.offerListingId; 
            } 
            set 
            {
                this.offerListingId = value;
                onPropertyChanged("OfferListingId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PricePerUnit")]
        public string PricePerUnit 
        { 
            get 
            {
                return this.pricePerUnit; 
            } 
            set 
            {
                this.pricePerUnit = value;
                onPropertyChanged("PricePerUnit");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Price")]
        public Models.Price Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SalePrice")]
        public Models.Price SalePrice 
        { 
            get 
            {
                return this.salePrice; 
            } 
            set 
            {
                this.salePrice = value;
                onPropertyChanged("SalePrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AmountSaved")]
        public Models.Price AmountSaved 
        { 
            get 
            {
                return this.amountSaved; 
            } 
            set 
            {
                this.amountSaved = value;
                onPropertyChanged("AmountSaved");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PercentageSaved")]
        public int? PercentageSaved 
        { 
            get 
            {
                return this.percentageSaved; 
            } 
            set 
            {
                this.percentageSaved = value;
                onPropertyChanged("PercentageSaved");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Availability")]
        public string Availability 
        { 
            get 
            {
                return this.availability; 
            } 
            set 
            {
                this.availability = value;
                onPropertyChanged("Availability");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AvailabilityAttributes")]
        public Models.AvailabilityAttributes AvailabilityAttributes 
        { 
            get 
            {
                return this.availabilityAttributes; 
            } 
            set 
            {
                this.availabilityAttributes = value;
                onPropertyChanged("AvailabilityAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsEligibleForSuperSaverShipping")]
        public bool? IsEligibleForSuperSaverShipping 
        { 
            get 
            {
                return this.isEligibleForSuperSaverShipping; 
            } 
            set 
            {
                this.isEligibleForSuperSaverShipping = value;
                onPropertyChanged("IsEligibleForSuperSaverShipping");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsEligibleForPrimeFreeDigitalVideo")]
        public bool? IsEligibleForPrimeFreeDigitalVideo 
        { 
            get 
            {
                return this.isEligibleForPrimeFreeDigitalVideo; 
            } 
            set 
            {
                this.isEligibleForPrimeFreeDigitalVideo = value;
                onPropertyChanged("IsEligibleForPrimeFreeDigitalVideo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsEligibleForPrime")]
        public bool? IsEligibleForPrime 
        { 
            get 
            {
                return this.isEligibleForPrime; 
            } 
            set 
            {
                this.isEligibleForPrime = value;
                onPropertyChanged("IsEligibleForPrime");
            }
        }
    }
} 