/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class OfferSummary : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Price lowestNewPrice;
        private Models.Price lowestUsedPrice;
        private Models.Price lowestCollectiblePrice;
        private Models.Price lowestRefurbishedPrice;
        private string totalNew;
        private string totalUsed;
        private string totalCollectible;
        private string totalRefurbished;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestNewPrice")]
        public Models.Price LowestNewPrice 
        { 
            get 
            {
                return this.lowestNewPrice; 
            } 
            set 
            {
                this.lowestNewPrice = value;
                onPropertyChanged("LowestNewPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestUsedPrice")]
        public Models.Price LowestUsedPrice 
        { 
            get 
            {
                return this.lowestUsedPrice; 
            } 
            set 
            {
                this.lowestUsedPrice = value;
                onPropertyChanged("LowestUsedPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestCollectiblePrice")]
        public Models.Price LowestCollectiblePrice 
        { 
            get 
            {
                return this.lowestCollectiblePrice; 
            } 
            set 
            {
                this.lowestCollectiblePrice = value;
                onPropertyChanged("LowestCollectiblePrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestRefurbishedPrice")]
        public Models.Price LowestRefurbishedPrice 
        { 
            get 
            {
                return this.lowestRefurbishedPrice; 
            } 
            set 
            {
                this.lowestRefurbishedPrice = value;
                onPropertyChanged("LowestRefurbishedPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalNew")]
        public string TotalNew 
        { 
            get 
            {
                return this.totalNew; 
            } 
            set 
            {
                this.totalNew = value;
                onPropertyChanged("TotalNew");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalUsed")]
        public string TotalUsed 
        { 
            get 
            {
                return this.totalUsed; 
            } 
            set 
            {
                this.totalUsed = value;
                onPropertyChanged("TotalUsed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalCollectible")]
        public string TotalCollectible 
        { 
            get 
            {
                return this.totalCollectible; 
            } 
            set 
            {
                this.totalCollectible = value;
                onPropertyChanged("TotalCollectible");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalRefurbished")]
        public string TotalRefurbished 
        { 
            get 
            {
                return this.totalRefurbished; 
            } 
            set 
            {
                this.totalRefurbished = value;
                onPropertyChanged("TotalRefurbished");
            }
        }
    }
} 