/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class OperationRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.HTTPHeaders hTTPHeaders;
        private string requestId;
        private Models.Arguments arguments;
        private Models.Errors errors;
        private double? requestProcessingTime;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HTTPHeaders")]
        public Models.HTTPHeaders HTTPHeaders 
        { 
            get 
            {
                return this.hTTPHeaders; 
            } 
            set 
            {
                this.hTTPHeaders = value;
                onPropertyChanged("HTTPHeaders");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId 
        { 
            get 
            {
                return this.requestId; 
            } 
            set 
            {
                this.requestId = value;
                onPropertyChanged("RequestId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Arguments")]
        public Models.Arguments Arguments 
        { 
            get 
            {
                return this.arguments; 
            } 
            set 
            {
                this.arguments = value;
                onPropertyChanged("Arguments");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Errors")]
        public Models.Errors Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RequestProcessingTime")]
        public double? RequestProcessingTime 
        { 
            get 
            {
                return this.requestProcessingTime; 
            } 
            set 
            {
                this.requestProcessingTime = value;
                onPropertyChanged("RequestProcessingTime");
            }
        }
    }
} 