/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;

namespace AWSECommerceService.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum PositiveIntegerOrAllEnum
    {
        ALL, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type PositiveIntegerOrAllEnum
    /// </summary>
    public static class PositiveIntegerOrAllEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "All" };

        /// <summary>
        /// Converts a PositiveIntegerOrAllEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The PositiveIntegerOrAllEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(PositiveIntegerOrAllEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case PositiveIntegerOrAllEnum.ALL:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of PositiveIntegerOrAllEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of PositiveIntegerOrAllEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<PositiveIntegerOrAllEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into PositiveIntegerOrAllEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed PositiveIntegerOrAllEnum value</returns>
        public static PositiveIntegerOrAllEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type PositiveIntegerOrAllEnum", value));

            return (PositiveIntegerOrAllEnum) index;
        }
    }
} 