/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class SavedForLaterItems : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.CartItem> savedForLaterItem;
        private Models.Price subTotal;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SavedForLaterItem")]
        public List<Models.CartItem> SavedForLaterItem 
        { 
            get 
            {
                return this.savedForLaterItem; 
            } 
            set 
            {
                this.savedForLaterItem = value;
                onPropertyChanged("SavedForLaterItem");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SubTotal")]
        public Models.Price SubTotal 
        { 
            get 
            {
                return this.subTotal; 
            } 
            set 
            {
                this.subTotal = value;
                onPropertyChanged("SubTotal");
            }
        }
    }
} 