/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class SearchBinSets : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.SearchBinSet> searchBinSet;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SearchBinSet")]
        public List<Models.SearchBinSet> SearchBinSet 
        { 
            get 
            {
                return this.searchBinSet; 
            } 
            set 
            {
                this.searchBinSet = value;
                onPropertyChanged("SearchBinSet");
            }
        }
    }
} 