/*
 * AWSECommerceService.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AWSECommerceService.Standard;
using AWSECommerceService.Standard.Utilities;


namespace AWSECommerceService.Standard.Models
{
    public class VariationSummary : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Price lowestPrice;
        private Models.Price highestPrice;
        private Models.Price lowestSalePrice;
        private Models.Price highestSalePrice;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestPrice")]
        public Models.Price LowestPrice 
        { 
            get 
            {
                return this.lowestPrice; 
            } 
            set 
            {
                this.lowestPrice = value;
                onPropertyChanged("LowestPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestPrice")]
        public Models.Price HighestPrice 
        { 
            get 
            {
                return this.highestPrice; 
            } 
            set 
            {
                this.highestPrice = value;
                onPropertyChanged("HighestPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LowestSalePrice")]
        public Models.Price LowestSalePrice 
        { 
            get 
            {
                return this.lowestSalePrice; 
            } 
            set 
            {
                this.lowestSalePrice = value;
                onPropertyChanged("LowestSalePrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("HighestSalePrice")]
        public Models.Price HighestSalePrice 
        { 
            get 
            {
                return this.highestSalePrice; 
            } 
            set 
            {
                this.highestSalePrice = value;
                onPropertyChanged("HighestSalePrice");
            }
        }
    }
} 